name: Run Go Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install gotestfmt
        run: |
          go install github.com/go-task/gotestfmt/v2/cmd/gotestfmt@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Make script executable
        run: chmod +x apps/backend/tests/run-tests.sh

      - name: Run Go tests
        working-directory: apps/backend/tests
        run: ./run-tests.sh
